### ISSUE TITLE
Some issues with the demo

### ISSUE THREAD

**Issue by jackkjhsu** [lekoala/data-grid#1]
Hi,

I am trying out this data-grid and found some issues as follows:

1. The Column Resizer plugin throws the following error:
Uncaught ReferenceError: DataGrid is not defined
    at HTMLDivElement.<anonymous> (column-resizer.js:86:9)
Fix on column-resizer.js:
`
import DataGrid from '../data-grid.js';  //line 2
...
max = DataGrid.elementOffset(e.target).left + grid.offsetWidth - remainingSpace; //line 86
`
2. Column Header context menu off alignment.
Fix on data-grid.css:
`position: relative; /* fixes alignment issue with context menu - added at line 35  */` 

Could we get these fixes applied to the source code?

Thank you

**Comment by lekoala** [comment]
Feel free to make a pr :) I'll gladly merge it. I'm not actively using this at the moment (I'm using tabulator instead) but i do have somewhere in my plans to work on improving things..

**Comment by jackkjhsu** [comment]
Hi Thomas,

Thanks for your reply. I just created a PR. Hopefully, they look good to merge from your end.

Also, I was wondering if you ever pick up this project again and would plan to add new features for printing and exporting to file format such as csv and pdf. Alternatively, any kind of resources that you could point me to to get started on making plugins for those new features would be great.

Thanks again

**Comment by lekoala** [comment]
@jackkjhsu yes, i do plan to work on it. and hopefully have a working plugin architecture, it's pretty barebones at the moment. Csv and pdf export is not very high on my list because i tend to do these server side since. the idea here is to have (mainly) a server side paginated grid, and therefore, it's kind of difficult to determine what to export: the whole data set (which could be huge)? only the current paginated view (which is not very useful?).
You might want to have a look at https://github.com/olifolkerd/tabulator which can probably do all that. And there is code in there that can be used as inspiration as well :)

**Comment by lekoala** [comment]
@jackkjhsu i've updated the project. I've changed quite a bit how plugins are working it should be much easier now to use them

**Comment by jackkjhsu** [comment]
Hi @lekoala,
Thanks for the update. I have some fixes coming for some more issues I encountered. I'll create another PR for them.
